### ISSUE TITLE
some problems with code execution

### ISSUE THREAD

**Issue by sbY99** [kolk/MultiTabQA#2]
Hi, thank you for your hard work.

After reviewing your paper, I attempted to execute the code but encountered a few issues.

1. It appears that I don't have the necessary access permissions to download any model checkpoints.
2. I couldn't locate the 'SpiderDataset' and 'utility' folders needed to run 'evaluate.py'.
3. I noticed a potential discrepancy in 'evaluate.py'. I believe the variable 'pretrained_model_name' should be 'args.pretrained_model_name' instead.

Could you please guide me on how to resolve these issues or direct me to any related information or code that could assist? 
Thanks.

**Comment by kolk** [comment]
Hi, thank you for your interest. I have updated the code and the model checkpoints. Please let me know if you face any other issues. :)

**Comment by sbY99** [comment]
Thank you for solving the issues quickly.
