### ISSUE TITLE
Dataset URL does not work

### ISSUE THREAD

**Issue by kpriyanshu256** [kolk/MultiTabQA#5]
The dataset url mentioned in data.txt does not work. My guess is the url expires after some time. If possible, can you please push the datasets to Huggingface?

**Comment by kolk** [comment]
Hi, thank you for your interest. The url should be working now.

**Comment by kolk** [comment]
I'll push the datasets to huggingface as well by next week.

**Comment by kolk** [comment]
The datasets have been uploaded to Huggingface.
